job("${DISPLAY_NAME}") {
    description("Job generated by the SEED job")

    properties {
        githubProjectUrl("https://github.com/${GITHUB_NAME}")
    }

    scm {
        git {
            remote {
                url("https://github.com/${GITHUB_NAME}.git")
            }
            branch("*/main")
        }
    }

    triggers {
        scm("* * * * *")
    }

    wrappers {
        preBuildCleanup()
    }

    steps {
        shell("make fclean")
        shell("make")
        shell("make tests_run")
        shell("make clean")
    }
}
